config/routes.rb
SimpleApp::Application.routes.draw do
  
  resources :profiles
  
  

   resources :users do
    member do
      get :following, :followers
    end
  end
  resources :sessions, only: [:new, :create, :destroy]
  resources :microposts, only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]

  root to: 'static_pages#home'
  match '/signup',  to: 'users#new'
  match '/help',    to: 'static_pages#help'
  match '/search',   to: 'static_pages#search'
  match '/about',   to: 'static_pages#about'
  match '/contact', to: 'static_pages#contact'
  match '/signin',  to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete
  match '/department', to: 'static_pages#department'
  match '/research', to: 'static_pages#research'

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def markdown(content)

  markdown =Redcarpet::Markdown.new(Redcarpet::Render::XHTML,:hard_wrap=>true,:filter_html=>true,:autolink=>true,:no_intra_emphasis=>true)
  markdown.render(content).html_safe

end
  def home
  	if signed_in?
      @micropost  = current_user.microposts.build
      @feed_items = current_user.feed.paginate(page: params[:page])
    end
  end

  def help
  end
  def about
  end 


  
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/_home.html.erb
  <div class="center hero-unit">
    <%= link_to image_tag("manipal.png", alt: "Rails"), '#' %>
    <br />
    <br />
    <h1>Welcome to the ITSpace </h1>

    

    <br />
    <h2>
      This is the home page for the I&CT Department Portal
    </h2>
    <%= link_to "Sign up now!", signup_path, 
                                class: "btn btn-large btn-primary" %>
  </div>

app/views/static_pages/about.html.erb
<% provide(:title, 'About Us') %>
<div class="container">
<h1>About Us</h1>
<p>
  This is a web portal for the IT department, where students can collaboratively discuss and solve problems. 
  It acts a discussion ground for teachers and students, where they can discuss topics online and excel in a better manner.
</p>
</div>

app/views/static_pages/contact.html.erb
<% provide(:title, 'Contact') %>
<div class="container">
<h1>Contact</h1>
<p>
  Contact  <b> Rishu Raj </b> for any information.
</p>
</div>

app/views/static_pages/department.html.erb
<% provide(:title, 'Department Home') %>

	<div id="manipal">
		<br /><br /><br />
		<div class="container" style=" -khtml-opacity:.50; 
 -moz-opacity:.50; 
 -ms-filter:”alpha(opacity=50)”;
  filter:alpha(opacity=50);
  filter: progid:DXImageTransform.Microsoft.Alpha(opacity=0.5);
  opacity:.50;
  background-color: black; 
  
  height: 200px;
  width: 690px;
  padding-left: 100px;
   ">
<div style="color: #D0C6B1; font-size: 46px;  font-family: Verdana, sans-serif; align: center">Information<br /><br /><br /> &<br /><br /><br />Communication Technology</div></div>
<img src="/assets/mit.png" style="height: 170px; width: 130px; padding-left: 150px" />
</div>


<br />

<div id="department">
<p style="font-size: 30px; font-family: Verdana, sans-serif; padding-left: 200px; color: #336699;">Faculty</p>
<div style="padding-left: 200px;">
<div id="teachers">
         <% for usr in User.all do %>
        
			<% if usr.designation=="teacher" %>
			<div id="teacher">	
				<% if usr.img != nil %>
				<img src= <%= usr.img %> style="height: 100px; width: 100px;"/>
				<% end %>
				<%= link_to usr.name, user_path(usr), :style => "color: black; text-decoration: none;" %>
			</div>
			<% end %>

			<% end %>
 </div>    
</div>
<h1>Academia</h1>
<% acad={} %>
  <% for user in User.all %>
  <% if user.designation=="teacher" %>
  <% @profile=user.profile %>
  <% @text=@profile.subjects.split(/\r?\n/) %>
    <% for i in 0..@text.length-1 %>
      <% @subj=@text[i].split(',')[0] %>
      <% @sem=@text[i].split(',')[1][0] %>
      <% @teachers=[] %>
      <% for usr in User.all %>
        <% if usr.designation=="teacher" %>
          <% @pro=usr.profile %>
          <% @sub=@pro.subjects.split(/\r?\n/) %>
          <% for @s in @sub %>
          <% if @s.include?(@subj) && @s.include?(@sem) %>
            <% @teachers.push(usr.name+"<br />") %>
            
        <% end %>
        <% end %>
      <% end %>
      <% end %>
      <% @teachers=@teachers.join %>
      <% acad[@subj+":"+@sem]=@teachers %>
    <% end %>
    <% end %>
    <% end %>
  
<div style="padding-left: 300px">
<table class="table">
  <tr>
    <th>Course Name</th>
    <th>Semester</th>
    <th>Faculty Teaching</th>
  </th>
  <% for key in acad.keys %>
  <tr>
    <td style="color: #D9D8BA; font-size: 16px"><%= key.split(':')[0] %></td>
    <td style="color: #D9D8BA; font-size: 16px"><%= key.split(':')[1] %></td>
    <td style="color: #D9D8BA; font-size: 16px"><%= markdown acad[key] %></td>
  </tr>
  <% end %>
  </table>
</div>
</div>

  
  
  

<script>
$(document).ready(function(){
	$('body').css('background-color','black');
});
</script>

app/views/static_pages/help.html.erb
<% provide(:title, 'Help') %>
<h1>Help</h1>
<p>
  This web page is currently under construction.
</p>

app/views/static_pages/home.html.erb
<% if signed_in? %>
<a href="<%= user_path(current_user) %>">
  <% if current_user.designation=="student" %>
  <%= render 'users/student' %>
  
  <% else %>
  <%= render 'users/show' %>
   
   

  <% end %>
<% else %>
  <div class="center hero-unit">
    <%= link_to image_tag("manipal.png", alt: "Rails"), 'http://www.manipal.edu' %>
    <br />
    <br />
    <span style="font-size: 50px;">Welcome to the ITSpace </span>
<!--
    <div class="span6">
    <div class="carousel slide" id="js-carousel">
      <div class="carousel-inner">
        <div class="active item">
          <img width="600" height="500" class="ws-responsive" src="http://www.shadygrove.umd.edu/sites/default/files/USG_Assets/Images/Campus/teacher-cartoon.jpg">
          <div class="carousel-caption">
            <h4>Collaborative Writing</h4>
            <p></p>
          </div>
        </div>
        <div class="item">
          <img width="600" height="500" class="ws-responsive" src="http://c1.wikicdn.com/i/edu-stream-2.png">
          <div class="carousel-caption">
            <h4>Social Writing</h4>
            <p></p>
          </div>
        </div>
        <div class="item">
          <img width="600" height="500" class="ws-responsive" src="http://c1.wikicdn.com/i/edu-assess-2.png">
          <div class="carousel-caption">
            <h4>Formative Assessment</h4>
            <p></p>
          </div>
        </div>
        <div class="item">
          <img width="600" height="500" class="ws-responsive" src="http://c1.wikicdn.com/i/edu-projects-2.png">
          <div class="carousel-caption">
            <h4>Classroom Management</h4>
            <p></p>
          </div>
        </div>
      </div>
      <a data-slide="prev" href="#js-carousel" class="left carousel-control">‹</a>
      <a data-slide="next" href="#js-carousel" class="right carousel-control">›</a>
    </div>
  </div>
-->
    <br />
    <br />
    <h2 style ="font-family: Arial;">
      This is the home page for the I&CT Department Portal
    </h2>
    <div style="padding-top: 8px;"></div>
    <br />
    <%= link_to "Sign up now!", signup_path, 
                                class: "btn btn-large btn-success" %>
  </div>

<% end %> 

app/views/static_pages/research.html.erb
<body style="background-color: #ffffff; padding-top:20px">

<div class="container" style="background-color:#ffffff;padding-top:0px; padding-left:20px">
	<h2 style="padding: 0px 0px 0px 0px; color: #CCCCCC; background-color: black">Welcome To The Research Portal</h2>
	<br />
	<div style="padding-left:140px; background-color: white">
	<table class="table">
	<tr>	
		<th style="padding-left:30px; text-decoration:underline">Faculty Name</th>
		<th style="padding-left:30px; text-decoration:underline">Research Details</th>
	</tr>
	<% for usr in User.all %>
	<% if usr.designation=="teacher" %>
	<% @profile=usr.profile %>
	<% @text=@profile.research.split(/\r?\n/) %>
    <% @text=@text.delete_if{|x| x==''} %>
    <% @books=[] %>
    <% for j in 0..((@text.length/2)-1) %>
        <% @books[j]=@text.slice!(0..1) %>
    <% end %>
      <% @books1=[] %>
    <% for j in @books %>
        <% j[0]="<br /><b style='color: black; font-size: 16px'>Field: </b> "+"<span style='font-size: 15px; color: #000'>"+j[0]+"</span><br />" %>
        <% j[1]="<b style='color: black; font-size: 16px'>Link: </b> "+"<span style='font-size: 15px'>"+j[1]+"</span><br />" %>
        <% @books1.push(j.flatten) %>
    <% end %>
    <% @profile.research=@books1.join %>
    <div class="container1" >
	<tr><ul>

		<td style="padding:35px 0px 0px 50px;"><li>

			<%= link_to usr.name, usr, :style => "font-size: 17px; font-family: Arial; text-decoration: none; color: #E06A1B" %>
			

		</li>

	</td></ul>
		<td style="padding:0px 0px 0px 40px;"><%= markdown(@profile.research) %></td></div>

	<% end %>


	<% end %>
	
</table>
</div>
</div>
</body>

app/views/static_pages/search.html.erb
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>ITSpace search</title>

<style type="text/css">



*{
  margin:0;
  padding:0;
}

body{
  font-size:13px;
  color:#eee;
  font-family:Arial, Helvetica, sans-serif;
  background:url('/assets/bg.jpg') repeat-x #718693;
}

#page{
  /* The main container div */
  width:620px;
  margin:40px auto 0;
}

h1{
  font-family:Corbel,'Myriad Pro',Arial, Helvetica, sans-serif;
  background:url('/assets/heading.png') no-repeat center top;
  text-indent:-9999px;
  overflow:hidden;
  height:90px;
}

#searchForm{
  /* The search form. */
  background-color:#4C5A65;
  padding:40px 50px 30px;
  margin:50px 0;
  position:relative;

  -moz-border-radius:16px;
  -webkit-border-radius:16px;
  border-radius:16px;
}

fieldset{
  border:none;
}

#searchInputContainer{
  /* This div contains the transparent search box */
  width:420px;
  height:46px;
  background:url("/assets/searchBox.png") no-repeat;
  float:left;
  margin-right:12px;
}

#s{
  /* The search text box. */
  
  border:none;
  color:#888888;
  background:url("/assets/searchBox.png") no-repeat;
  
  float:left;
  font-family:Arial,Helvetica,sans-serif;
  font-size:15px;
  height:86px;
  line-height:36px;
  margin-right:12px;
  outline:medium none;
  padding:6px 0 10px 35px;
  text-shadow:1px 1px 0 white;
  width:420px;
}

/* The UL that contains the search type icons */

.icons{
  list-style:none;
  margin:10px 0 0 305px;
  height:19px;
  position:relative;
}

.icons li{
  background:url("/assets/icons.png") no-repeat;
  float:left;
  height:19px;
  text-indent:-9999px;
  cursor:pointer;
  margin-right:5px;
}

/* Styling each icon */

li.web{ width:15px;}
li.web.active,
li.web:hover{ background-position:left bottom;}

li.images{ width:22px; background-position:-18px 0;}
li.images.active,
li.images:hover{ background-position:-18px bottom;}

li.news{ width:14px; background-position:-44px 0;}
li.news.active,
li.news:hover{ background-position:-44px bottom;}

li.videos{ width:17px; background-position:right 0;}
li.videos.active,
li.videos:hover{ background-position:right bottom;}

span.arrow{
  /* The little arrow that moves below the icons */
  
  width:11px;
  height:6px;
  margin:21px 0 0 5px;
  position:absolute;
  background:url('/assets/arrow.png') no-repeat;
  left:0;
}


/* The submit button */


#submitButton{
  background:url('/assets/buttons.png') no-repeat;
  width:83px;
  height:46px;
  text-indent:-9999px;
  overflow:hidden;
  text-transform:uppercase;
  padding:1px 0 17px 0px;
  border:none;
  cursor:pointer;
}

#submitButton:hover{
  background-position:0px -36px;
}


/* The Search tutorialzine.com / Search the Web radio buttons */


#searchInContainer{
  float:left;
  margin-top:12px;
  width:330px;
}

label{
  color:#DDDDDD;
  cursor:pointer;
  font-size:11px;
  position:relative;
  right:-2px;
  top:-2px;
  margin-right:10px;
  white-space:nowrap;
  /*float:left;*/
}

input[type=radio]{
  cursor:pointer;
  /*float:left;*/
}


/* Styling the search results */


.pageContainer{
  /* Holds each page with search results. Has an inset bottom border. */
  border-bottom:1px solid #5e7481;
  margin-bottom:50px;
  
  /* Adding a dark bottom border with box shadow */
  
  -moz-box-shadow:0 1px 0 #798e9c;
  -webkit-box-shadow:0 1px 0 #798e9c;
  box-shadow:0 1px 0 #798e9c;
}


p.notFound{
  text-align:center;
  padding:0 0 40px;
}


/* Web & news results */


.webResult{ text-shadow:1px 1px 0 #586a75;margin-bottom:50px;}
.webResult h2{ 
  background-color:#5D6F7B;
  font-size:18px;
  font-weight:normal;
  padding:8px 20px;
  
  /* Applying CSS3 rounded corners */
  -moz-border-radius:18px;
  -webkit-border-radius:18px;
  border-radius:18px;
}
.webResult h2 b{ color:#fff; }
.webResult h2 a{ color:#eee;border:none;}
.webResult p{ line-height:1.5;padding:15px 20px;}
.webResult p b{ color:white;}
.webResult > a{ margin-left:20px;}


/* Image & video search results */


.imageResult{
  float:left;
  height:180px;
  margin:0 0 20px 40px;
  text-align:center;
  width:152px;
  overflow:hidden;
}
.imageResult img{ display:block;border:none;}
.imageResult a.pic{
  border:1px solid #fff;
  outline:1px solid #777;
  display:block;
  margin:0 auto 15px;
}

/* The show more button */

#more{
  width:83px;
  height:24px;
  background:url('/assets/more.png') no-repeat;
  cursor:pointer;
  margin:40px auto;
}

#more:hover{
  background-position:left bottom;
}



/* Giving Credit */

p.credit{
  margin:20px 0;
  text-align:center;
}

p.credit a{
  background-color:#4B5A64;
  border:1px solid;
  border-color:#3D4D57 #788E9B #788E9B #3D4D57;
  color:#c0d0d8;
  font-size:10px;
  padding:4px 8px;
  text-shadow:1px 1px 0 #38464F;
}

p.credit a:hover{
  background-color:#38464f;
  border-color:#38464f #788E9B #788E9B #38464f;
}

a, a:visited {
  text-decoration:none;
  outline:none;
  border-bottom:1px dotted #97cae6;
  color:#97cae6;
}

a:hover{
  border-bottom:1px dashed transparent;
}

.clear{
  clear:both;
}


</style>

</head>

<body>

<div id="page">

    <h1>Google Powered Site Search</h1>
    
    <form id="searchForm" method="post">
        <fieldset>
        
            <input id="s" type="text" />
            
            <input type="submit" value="Submit" id="submitButton" />
            
            <div id="searchInContainer">
                <input type="radio" name="check" value="site" id="searchSite" checked />
                <label for="searchSite" id="siteNameLabel">Search</label>
                
                <input type="radio" name="check" value="web" id="searchWeb" />
                <label for="searchWeb">Search The Web</label>
            </div>
                        
            <ul class="icons">
                <li class="web" title="Web Search" data-searchType="web">Web</li>
                <li class="images" title="Image Search" data-searchType="images">Images</li>
                <li class="news" title="News Search" data-searchType="news">News</li>
                <li class="videos" title="Video Search" data-searchType="video">Videos</li>
            </ul>
            
        </fieldset>
    </form>

    <div id="resultsDiv"></div>
    
</div>

    
<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.4.2/jquery.min.js"></script>
<script type="text/javascript">
$(document).ready(function(){
    
    var config = {
        siteURL     : 'http://www.ITSpace.com', // Change this to your site
        searchSite  : true,
        type        : 'web',
        append      : false,
        perPage     : 8,            // A maximum of 8 is allowed by Google
        page        : 0             // The start page
    }
    
    // The small arrow that marks the active search icon:
    var arrow = $('<span>',{className:'arrow'}).appendTo('ul.icons');
    
    $('ul.icons li').click(function(){
        var el = $(this);
        
        if(el.hasClass('active')){
            // The icon is already active, exit
            return false;
        }
        
        el.siblings().removeClass('active');
        el.addClass('active');
        
        // Move the arrow below this icon
        arrow.stop().animate({
            left        : el.position().left,
            marginLeft  : (el.width()/2)-4
        });
        
        // Set the search type
        config.type = el.attr('data-searchType');
        $('#more').fadeOut();
    });
    
    // Adding the site domain as a label for the first radio button:
    $('#siteNameLabel').append(' '+config.siteURL);
    
    // Marking the Search tutorialzine.com radio as active:
    $('#searchSite').click();   
    
    // Marking the web search icon as active:
    $('li.web').click();
    
    // Focusing the input text box:
    $('#s').focus();

    $('#searchForm').submit(function(){
        googleSearch();
        return false;
    });
    
    $('#searchSite,#searchWeb').change(function(){
        // Listening for a click on one of the radio buttons.
        // config.searchSite is either true or false.
        
        config.searchSite = this.id == 'searchSite';
    });
    
    
    function googleSearch(settings){
        
        // If no parameters are supplied to the function,
        // it takes its defaults from the config object above:
        
        settings = $.extend({},config,settings);
        settings.term = settings.term || $('#s').val();
        
        if(settings.searchSite){
            // Using the Google site:example.com to limit the search to a
            // specific domain:
            settings.term = 'site:'+settings.siteURL+' '+settings.term;
        }
        
        // URL of Google's AJAX search API
        var apiURL = 'http://ajax.googleapis.com/ajax/services/search/'+settings.type+'?v=1.0&callback=?';
        var resultsDiv = $('#resultsDiv');
        
        $.getJSON(apiURL,{q:settings.term,rsz:settings.perPage,start:settings.page*settings.perPage},function(r){
            
            var results = r.responseData.results;
            $('#more').remove();
            
            if(results.length){
                
                // If results were returned, add them to a pageContainer div,
                // after which append them to the #resultsDiv:
                
                var pageContainer = $('<div>',{className:'pageContainer'});
                
                for(var i=0;i<results.length;i++){
                    // Creating a new result object and firing its toString method:
                    pageContainer.append(new result(results[i]) + '');
                }
                
                if(!settings.append){
                    // This is executed when running a new search, 
                    // instead of clicking on the More button:
                    resultsDiv.empty();
                }
                
                pageContainer.append('<div class="clear"></div>')
                             .hide().appendTo(resultsDiv)
                             .fadeIn('slow');
                
                var cursor = r.responseData.cursor;
                
                // Checking if there are more pages with results, 
                // and deciding whether to show the More button:
                
                if( +cursor.estimatedResultCount > (settings.page+1)*settings.perPage){
                    $('<div>',{id:'more'}).appendTo(resultsDiv).click(function(){
                        googleSearch({append:true,page:settings.page+1});
                        $(this).fadeOut();
                    });
                }
            }
            else {
                
                // No results were found for this search.
                
                resultsDiv.empty();
                $('<p>',{className:'notFound',html:'No Results Were Found!'}).hide().appendTo(resultsDiv).fadeIn();
            }
        });
    }
    
    function result(r){
        
        // This is class definition. Object of this class are created for
        // each result. The markup is generated by the .toString() method.
        
        var arr = [];
        
        // GsearchResultClass is passed by the google API
        switch(r.GsearchResultClass){

            case 'GwebSearch':
                arr = [
                    '<div class="webResult">',
                    '<h2><a href="',r.unescapedUrl,'" target="_blank">',r.title,'</a></h2>',
                    '<p>',r.content,'</p>',
                    '<a href="',r.unescapedUrl,'" target="_blank">',r.visibleUrl,'</a>',
                    '</div>'
                ];
            break;
            case 'GimageSearch':
                arr = [
                    '<div class="imageResult">',
                    '<a target="_blank" href="',r.unescapedUrl,'" title="',r.titleNoFormatting,'" class="pic" style="width:',r.tbWidth,'px;height:',r.tbHeight,'px;">',
                    '<img src="',r.tbUrl,'" width="',r.tbWidth,'" height="',r.tbHeight,'" /></a>',
                    '<div class="clear"></div>','<a href="',r.originalContextUrl,'" target="_blank">',r.visibleUrl,'</a>',
                    '</div>'
                ];
            break;
            case 'GvideoSearch':
                arr = [
                    '<div class="imageResult">',
                    '<a target="_blank" href="',r.url,'" title="',r.titleNoFormatting,'" class="pic" style="width:150px;height:auto;">',
                    '<img src="',r.tbUrl,'" width="100%" /></a>',
                    '<div class="clear"></div>','<a href="',r.originalContextUrl,'" target="_blank">',r.publisher,'</a>',
                    '</div>'
                ];
            break;
            case 'GnewsSearch':
                arr = [
                    '<div class="webResult">',
                    '<h2><a href="',r.unescapedUrl,'" target="_blank">',r.title,'</a></h2>',
                    '<p>',r.content,'</p>',
                    '<a href="',r.unescapedUrl,'" target="_blank">',r.publisher,'</a>',
                    '</div>'
                ];
            break;
        }
        
        // The toString method.
        this.toString = function(){
            return arr.join('');
        }
    }
    
    
});

</script>
</body>
</html>