config/routes.rb
SimpleApp::Application.routes.draw do
  
  resources :profiles
  
  

   resources :users do
    member do
      get :following, :followers
    end
  end
  resources :sessions, only: [:new, :create, :destroy]
  resources :microposts, only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]

  root to: 'static_pages#home'
  match '/signup',  to: 'users#new'
  match '/help',    to: 'static_pages#help'
  match '/search',   to: 'static_pages#search'
  match '/about',   to: 'static_pages#about'
  match '/contact', to: 'static_pages#contact'
  match '/signin',  to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete
  match '/department', to: 'static_pages#department'
  match '/research', to: 'static_pages#research'

end

app/models/user.rb
class User < ActiveRecord::Base
  
  attr_accessible :clas, :uid, :img, :name, :email, :password, :password_confirmation, :designation, :group_url
  has_secure_password
  has_many :microposts, dependent: :destroy
  has_many :relationships, foreign_key: "follower_id", dependent: :destroy
  has_many :followed_users, through: :relationships, source: :followed
  has_many :reverse_relationships, foreign_key: "followed_id",
                                   class_name:  "Relationship",
                                   dependent:   :destroy
  has_many :memberships 
  has_many :groups, :through => :memberships

  has_many :followers, through: :reverse_relationships, source: :follower
  has_one :profile
  before_save { |user| user.email = email.downcase }
  before_save :create_remember_token
  
  def feed
    Micropost.from_users_followed_by(self)
  end
   def following?(other_user)
    relationships.find_by_followed_id(other_user.id)
  end

  def follow!(other_user,type)
    relationships.create!(followed_id: other_user.id, join_type: type)
  end
   def unfollow!(other_user)
    relationships.find_by_followed_id(other_user.id).destroy
  end
  private
 
    


  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence:   true,
                    format:     { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  validates :password, presence: true, length: { minimum: 6 }
  validates :password_confirmation, presence: true

  def create_remember_token
      self.remember_token = SecureRandom.urlsafe_base64
    end
   
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
   before_filter :signed_in_user, 
                only: [:index, :edit, :update, :destroy, :following, :followers]
   before_filter :correct_user,   only: [:edit, :update]
    before_filter :admin_user,     only: :destroy

 def new
  @user= User.new
  if signed_in? and !current_user.admin
    redirect_to current_user
  end
  end
  def edit
    @user = User.find(params[:id])
  end

  def following
    @title = "Following"
    @user = User.find(params[:id])
    @users = @user.followed_users.paginate(page: params[:page])
    render 'show_follow'
  end
  def followers
    @title = "Followers"
    @user = User.find(params[:id])
    @users = @user.followers.paginate(page: params[:page])
    render 'show_follow'
  end
  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "User destroyed."
    redirect_to users_url
  end
  def index
    @users = User.paginate(page: params[:page])
  end
  def update
    @user = User.find(params[:id])
    if @user.update_attributes(params[:user])
      flash[:success] = "Profile updated"
      sign_in @user
      redirect_to @user
    else
      render 'edit'
    end
  end
  def show
    @arr = Array.new
    @user = User.find(params[:id])
    #@user.img=markdown("<img src="+@user.img+" />")
    if @user.designation=="student"
      render 'student'
    elsif @user.designation=="class"
      render 'class'
    else 
     @microposts = @user.microposts.paginate(page: params[:page])

      @profile=@user.profile
      @text=@profile.research.split(/\r?\n/)
      @text=@text.delete_if{|x| x==''}
      @books=[]
      for j in 0..((@text.length/2)-1)
        @books[j]=@text.slice!(0..1)
      end
      @books1=[]
      for j in @books
        j[0]="<br /><b style='color: black'>Field: </b> "+j[0]+"<br />"
        j[1]="<b style='color: black'>Link: </b> "+j[1]+"<br />"
        @books1.push(j.flatten)
      end
      @profile.research=@books1.join

    @text=@profile.collaborators.split(/\r?\n/)
    @text=@text.delete_if{|x| x==''}
    @collabs=[]
    for i in 0..((@text.length/2)-1)
      @collabs[i]=@text.slice!(0..1)
    end
    @collabs1=[]
    for c in @collabs
      c[0]="<h5><u>"+c[0]+"</u></h5>"
      c[1]="<h6>-"+c[1]+"</h6><br />"
      @collabs1.push(c.flatten)
    end
    @profile.collaborators=@collabs1.join

    
    @text=@profile.subjects.split(/\r?\n/)
    for i in 0..@text.length-1
      @class=@text[i].split(',')[1]
      @text[i]=@text[i].split(',')[0]
      @text[i]="<br />"+"<li style='color:#000; font-size: 15px'>"+@text[i]+": "+@class+"</li>"+"<br />"
    end
    @profile.subjects="<ul>"+@text.join+"</ul>"
  
    @text=@profile.current_students.split(/\r?\n/)
    for i in 0..@text.length-1
      @text[i]="<br />"+"<li>"+@text[i]+"</li>"+"<br />"
    end
    @profile.current_students="<ul>"+@text.join+"</ul>" 
    
    @text=@profile.conferences.split(/\r?\n/)
   @text=@text.delete_if{|x| x==''}  
    @journals=[]
    for j in 0..((@text.length/6)-1)
      @journals[j]=@text.slice!(0..5)
    end
    @journals1=[]
    for j in @journals
    j[0]="<br /><h5 style='color:blue'><u>"+j[0]+"</u></h5>"
    j[1]="<span style='color: #000'>"+j[1]+"</span><br /><br />"
    j[2]="<h3>"+j[2]+"</h3>"
    j[3]="<span style='color: #000'>"+j[3]+"</span><br /><br />"
    j[4]="Month/Year: "+"<span style='color: #000'>"+j[4]+"</span><br /><br />"
    j[5]="Page(s): "+"<span style='color: #000'>"+j[5]+"</span><br /><br /><hr />"
    @journals1.push(j.flatten)
    
    end
    @profile.conferences=@journals1.join

    @text=@profile.journals.split(/\r?\n/)
    @text=@text.delete_if{|x| x==''}  
    @journals=[]
    for j in 0..((@text.length/5)-1)
      @journals[j]=@text.slice!(0..4)
    end
    @journals1=[]
    for j in @journals
    j[0]="<h5 style='color:blue'><u>"+j[0]+"</u></h5>"
    j[1]="<span style='color: blue; font-size: 12px'>"+j[1]+"</span><br /><br />"
    j[2]="Volume,Issue: "+"<span style='color: black'>"+j[2]+"</span><br /><br />"
    j[3]="Publication Year: "+"<span style='color: black'>"+j[3]+"</span><br /><br />"
    j[4]="Page(s): "+"<span style='color: black'>"+j[4]+"</span><br /><hr />"
    @journals1.push(j.flatten)
    end
    
    @profile.journals=@journals1.join
  
    @text=@profile.books.split(/\r?\n/)
    @text=@text.delete_if{|x| x==''}
    @books=[]
    for j in 0..((@text.length/6)-1)
      @books[j]=@text.slice!(0..5)
    end
    @books1=[]
    for j in @books
    j[0]="<br /><h3><u>"+j[0]+"</u></h3>"
    j[1]="<span style='color: #D9D8BA'>"+j[1]+"</span><br /><br />"
    j[2]="<u>Publisher</u>: "+"<span style='color: #D9D8BA'>"+j[2]+"</span><br /><br />"
    j[3]="<u>Edition</u>: "+"<span style='color: #D9D8BA'>"+j[3]+"</span><br /><br />"
    j[4]="<u>Year</u>: "+"<span style='color: #D9D8BA'>"+j[4]+"</span><br /><br />"
    j[5]="<span style='color: #D9D8BA'>"+j[5]+"</span><br /><br /><hr />"
    @books1.push(j.flatten)
    end
    @profile.books=@books1.join

    @text=@profile.monogram.split(/\r?\n/)
    @text=@text.delete_if{|x| x==''}
    @monograms=[]
    for j in 0..((@text.length/4)-1)
      @monograms[j]=@text.slice!(0..3)
    end
    @monograms1=[]
    for j in @monograms
    j[0]="<br /><h3><u>"+j[0]+"</u></h3>"
    j[1]="<span style='color: #D9D8BA'>"+j[1]+"</span><br /><br />"
    j[2]="<u>Publisher</u>: "+"<span style='color: #D9D8BA'>"+j[2]+"</span><br /><br />"
    j[3]="<u>Year</u>: "+"<span style='color: #D9D8BA'>"+j[3]+"</span><br /><br /><hr />"
    @monograms1.push(j.flatten)
    end
    @profile.monogram=@monograms1.join
    
    end
  end
  def create
    @user = User.new(params[:user])
    if @user.save
      if @user.designation=="teacher" 
        if @user.uid=="mumit@123"
            #UserMailer.registration_confirmation(@user).deliver
            redirect_to new_profile_path
            sign_in @user
            return
        else 
          @user.destroy
          redirect_to new_user_path
          flash[:error] = "Incorrect Unique Id"
          return 
        end
    elsif @user.designation=="class"
          redirect_to :back
          return
    else
      #UserMailer.registration_confirmation(@user).deliver
      sign_in @user
    end
    flash[:success] = "Welcome, #{@user.name}"
     redirect_to @user
     
    else
      render 'new'
    end
  end
  private

    def signed_in_user
      unless signed_in?
        store_location
        redirect_to signin_url, notice: "Please sign in."
      end
    end
    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_path) unless current_user?(@user)
    end
    def admin_user
      redirect_to(root_path) unless current_user.admin?
    end
end

app/helpers/users_helper.rb
module UsersHelper

  # Returns the Gravatar (http://gravatar.com/) for the given user.
  def gravatar_for(user)
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/views/users/_comment.html.erb
<div>
<h4>Comment by <%= comment.author_name %></h4>
<p class="comment"><%= comment.body %></p>
</div>

app/views/users/_follow.html.erb

<%= form_for(current_user.relationships.build(followed_id: @user.id)) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>
      <% if current_user.designation=="student" %>
      
      <div id="something" style="color: #0000FF; background-color:#ffffff; text-align: right; float: left">
       
       <%= f.radio_button :join_type, "Credit", :id => 'Credits' %> Credit 
      
      &nbsp;&nbsp; &nbsp;<br />&nbsp;&nbsp;<br />
        
       <%= f.radio_button :join_type, "Audit", :id => 'Audits' %>&nbsp;Audit &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<br />  
        
        

    </div>
        
    <% end %>
    
  <div><%= f.hidden_field :followed_id %></div>
  <%= f.submit "Join Class", :class => "cnt" %>
<% end %>

app/views/users/_follow_form.html.erb
<% unless current_user?(@user) %>
  <div id="follow_form">
  <% if current_user.following?(@user) %>
    <%= render 'unfollow' %>
  <% else %>
    <%= render 'follow' %>
  <% end %>
  </div>
<% end %>

app/views/users/_show.html.erb
<body style="background-color: #ffffff">
<div class="container">
<a href="<%= user_path(current_user) %>">
<% provide(:title, current_user.name) %>
<div class="row">
  <aside class="span4" style="background-color: #000000; ">
    <div style="padding-bottom: 30px">
    <section>
      <h1>
        <span style="padding: 5px"><img src= <%= current_user.img %> /></span>
        <span style="color: #FF660F; font-size: 35px; font-family: Trebuchet MS, serif; text-align: left; padding-top: 27px; padding-left: 15px; color: #CCCCCC;"><%= current_user.name %></span>
      </h1>
    </section>
    </div>
    <section>
      <%= render 'shared/stats' %>
    </section>
     
  </aside>
  <aside class="span7">
  <div class="profile">
    <%= render '/profiles/show1' %>
  </div>
  <%= link_to 'Edit Info', edit_profile_path(current_user.profile), :style => "text-decoration: none" %>
  
  <section>
    <%= render 'shared/micropost_form1' %>
  </section>
</aside>
  </div>
</div></body>

app/views/users/_student.html.erb
<div class="container">
<% provide(:title, current_user.name) %>
<div class="row">
  <div class="span4" style="background-color: #000000; width:30%">
    <div style="padding-bottom: 30px">
    <section>
      <h1>
        <span style="padding: 5px"><img src= "<%= current_user.img %>" style="width: 96%" /></span>
        <span style="color: #FF660F; font-size: 35px; font-family: Trebuchet MS, serif; text-align: left; padding-top: 27px; padding-left: 15px; color: #CCCCCC;"><%= current_user.name %></span>
      </h1>
    </section>
    </div>
  </div>
  
 </div>
</div>

app/views/users/_unfollow.html.erb
<%= form_for(current_user.relationships.find_by_followed_id(@user),
             html: { method: :delete },
             remote: false) do |f| %>
  <%= f.submit "Leave Class", :class => "ab" %>
<% end %>

app/views/users/_user.html.erb
<li>
  <img src="<%= user.img %>" style = "height : 30px; width: 40px;align: center; padding-left: 10px" alt="Pic"/>
  <%= link_to user.name, user %> &nbsp; &nbsp; &nbsp; &nbsp; <%= user.email %>
  <% if current_user.admin? && !current_user?(user) %>
    | <%= link_to "delete", user, method: :delete,
                                  data: { confirm: "You sure?" } %>
  <% end %>
  
</li>

app/views/users/class.html.erb
<head>
  <style type="text/css">
  .highlight {
  background-color: #fff34d;
  -moz-border-radius: 5px; /* FF1+ */
  -webkit-border-radius: 5px; /* Saf3-4 */
  border-radius: 5px; /* Opera 10.5, IE 9, Saf5, Chrome */
  -moz-box-shadow: 0 1px 4px rgba(0, 0, 0, 0.7); /* FF3.5+ */
  -webkit-box-shadow: 0 1px 4px rgba(0, 0, 0, 0.7); /* Saf3.0+, Chrome */
  box-shadow: 0 1px 4px rgba(0, 0, 0, 0.7); /* Opera 10.5+, IE 9.0 */
  }
   
  .highlight {
  padding:1px 4px;
  margin:0 -4px;
  }
  </style>

  <script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1/jquery.min.js"></script>
  <script type="text/javascript">
  /*
   
  highlight v3 !! Modified by Jon Raasch (http://jonraasch.com) to fix IE6 bug !!
   
  Highlights arbitrary terms.
   
  <http://johannburkard.de/blog/programming/javascript/highlight-javascript-text-higlighting-jquery-plugin.html>
   
  MIT license.
   
  Johann Burkard
  <http://johannburkard.de>
  <mailto:jb@eaio.com>
   
  */
   
  jQuery.fn.highlight = function(pat) {
  function innerHighlight(node, pat) {
  var skip = 0;
  if (node.nodeType == 3) {
  var pos = node.data.toUpperCase().indexOf(pat);
  if (pos >= 0) {
  var spannode = document.createElement('span');
  spannode.className = 'highlight';
  var middlebit = node.splitText(pos);
  var endbit = middlebit.splitText(pat.length);
  var middleclone = middlebit.cloneNode(true);
  spannode.appendChild(middleclone);
  middlebit.parentNode.replaceChild(spannode, middlebit);
  skip = 1;
  }
  }
  else if (node.nodeType == 1 && node.childNodes && !/(script|style)/i.test(node.tagName)) {
  for (var i = 0; i < node.childNodes.length; ++i) {
  i += innerHighlight(node.childNodes[i], pat);
  }
  }
  return skip;
  }
  return this.each(function() {
  innerHighlight(this, pat.toUpperCase());
  });
  };
   
  jQuery.fn.removeHighlight = function() {
  function newNormalize(node) {
  for (var i = 0, children = node.childNodes, nodeCount = children.length; i < nodeCount; i++) {
  var child = children[i];
  if (child.nodeType == 1) {
  newNormalize(child);
  continue;
  }
  if (child.nodeType != 3) { continue; }
  var next = child.nextSibling;
  if (next == null || next.nodeType != 3) { continue; }
  var combined_text = child.nodeValue + next.nodeValue;
  new_node = node.ownerDocument.createTextNode(combined_text);
  node.insertBefore(new_node, child);
  node.removeChild(child);
  node.removeChild(next);
  i--;
  nodeCount--;
  }
  }
   
  return this.find("span.highlight").each(function() {
  var thisParent = this.parentNode;
  thisParent.replaceChild(this.firstChild, this);
  newNormalize(thisParent);
  }).end();
  };
  </script>
  <script type="text/javascript">
  $(function() {
  $('#text-search').bind('keyup change', function(ev) {
  // pull in the new value
  var searchTerm = $(this).val();
   
  // remove any old highlighted terms
  $('#remove-this').removeHighlight();
  $('body').removeHighlight();


   
  // disable highlighting if empty
  if ( searchTerm ) {
  // highlight the new term
  $('#search-this2').highlight( searchTerm );
  }
  });
  });
  </script>
</head>

<body>
<div class="row" style="padding-left:30px; background-color: #e7e5e5; padding-top: 10px; " >
  <div class="span4" style="padding-left: 10px; background-color: #ffffff; width: 285px; border-radius: 3px">
    <br />
    <div style="padding-left: 20px; padding-bottom: 20px; width: 200px">
      <% if @user.img!="" %>
      <img src="<%= @user.img %>" style = "height : 120px; width: 130px;align: center; padding-left: 50px"/>
      <% else %>
      <img src="http://www.lawgazette.co.uk/files/images/classroom-cartoon.jpg" style = "height : 120px; width: 130px;align: center; padding-left: 50px"/>
      <% end %>
    </div>
    <h4 style="padding-left: 25px; font-family: Verdana, sans-serif; color: gray; font-weight: bold">Teachers</h4>
    <table class="table">
      <% for user in @user.followers.all.each do %>
      <% if user.designation=="teacher" %>
      <% @profile=user.profile %>
      <% @text=@profile.subjects.split(/\r?\n/) %>
      <% for i in 0..@text.length-1 %>
          <% @class=@text[i].split(',')[1] %>
          <% @subj=@text[i].split(',')[0] %>
          <% if @class==@user.name %>
            <% subject=@subj %>
          <% end %>
      <% end %>
      <tr><td><img src="<%= user.img %>" style="padding-left: 20px; height: 30px; width: 40px;">&nbsp;&nbsp;<%= link_to user.name, user %></td><td style="padding-top: 10px; color: #BF0D55"><b><%= subject %></b>
      </td></tr> 
      <% end %>
      <% end %>
    </table>
    <br />
    <div style="padding-left:10px">
            <hr style="border-bottom: 1px solid lightgray; width: 260px"/>
    </div>

    <h4 style="padding-left:25px; font-family: Verdana, sans-serif; color: gray; font-weight: bold">Students</h4>
    <table class="table table-striped">
      <% for user in @user.followers.all.each do %>
        <% if user.designation=="student" %>
          <tr><td><img src="<%= user.img %>" style="padding-left: 20px; height: 30px; width: 40px;">&nbsp;&nbsp;<%= link_to user.name, user %>
          </td></tr> 
        <% end %>
      <% end %>
    </table>
  </div>

  <div class="span8" id="search-this1" style="background-color: #ffffff; width: 655px; padding-top: 5px; border-radius: 3px">
    <!-- border-left&#58;1px solid lightgray; margin-left&#58;16px; &#35; -->
    <center style="padding-top: 0px">
      <div style="text-align: left; height: 1px; padding-left: 30px; padding-top: 30px; background-color: #ffffff">
        <span style="color: black; font-size: 22px; font-family: Verdana, sans-serif; font-weight: bold">
         CLASS&nbsp;<%= @user.name %> &nbsp; 
        </span>
          
         <div style="text-align:left; padding: 15px 0px 0px 0px">
        Welcome to Class <%= @user.name %> at MIT, Manipal.<br />
        
        <br />
          </div> 
      </div>  
      <div style="text-align: right; padding-left: 410px; padding-right: 10px; background-color: #ffffff">
        <%= render 'follow_form' if (signed_in? && !current_user.admin? ) %></div>
        <div style="width:230px; padding-left:390px">

        Search: <input type="text" id="text-search" />
        </div>
    </center>
    
    <% if current_user.admin? && !current_user?(user) %>
      <div style="padding-left: 410px; padding-bottom:10px">  <%= link_to "Delete Class", user, method: :delete,
                                    data: { confirm: "You sure?" }, :class => "ab" %>
      </div>
    <% end %>
     <br />
     <div class="separator">
       <span style="color: gray; font-weight: bold; font-size:12px">RECENT POSTS</span>
     </div>

     <br />

    <% if current_user.following?(@user) or current_user.admin? %>
      <% for user in @user.followers.all.each do %>
        <% if user.microposts.any? %>
          <% for post in user.microposts %>
            <% if post.group_id==@user.id %>
              <% @arr.push(post.id)%>
            <% end %>
          <% end %>
        <% end %>
      <% end %>

      <% @arr.sort! %>
      <% @arr.reverse! %>
      <div id="search-this2">
      <% @arr.each do|m| %>

        <%  for post in Micropost.all %>
          <% if post.id==m %>
              <div style="height: 30px; text-align:top; padding-left: 10px" id="remove-this">
                <h4><img src="<%= post.user.img %>" style="height: 35px; width: 45px;">&nbsp;&nbsp;<%= link_to post.user.name, post.user %>
                  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                <% if post.tyype=="Assignment" %>
                    <span style="text-align:right; font-size:15px; color: red">Assignment</span>

                  <% end %></h4>
              </div>
              
              <div style="padding-left:70px" id="search-this">
                
                <span class="content" style="padding-right:10px; font-size:13px"><%= markdown(post.content) %>

                </span>
                <% if post.attach.exists? %>
                  <a href="<%= post.attach.url %>">
                  <b><%= post.attach_file_name %></b></a>
                  <br />
                <% end %>
                
       
                <span class="timestamp">
                Posted <%= time_ago_in_words(post.created_at) %> ago.
                </span>


                <% if current_user?(post.user) %>
                  <%= link_to "delete", post, method: :delete,
                                           data: { confirm: "You sure?" },
                                           title: post.content %>
                <% end %>
                
              </div>
              <div style="padding-left:10px">
                <hr style="border-bottom: 2px lightgray; width: 635px; align:center"/>
              </div>

          <% end %>
        <% end %>
    
      <% end %>
    </div>
  
  </div>

  <div class="span4" style="padding-left: 10px;background-color: #ffffff; width: 230px; height: 600px; border-radius: 3px" >
    <h4 style="color:gray">Assignments</h4>
    <table class="table">
      <tr>
        <th id="as" style="font-size:14px">Faculty</th>
        <th id="as" style="font-size:14px">Deadline</th>
      </tr>
    <% @arr.each do |m| %>
    <% for post in Micropost.all %>
      <% if post.id == m %>
        <% if post.tyype=="Assignment" %>
          
            <tr>
              <td><%= post.user.name %></td>
              <td><strong><span style="color: brown"><%= (Date.parse(post.deadline)).strftime("%a,%d %b %y") %><br /><small>(<%= ((Date.parse(post.deadline)).strftime("%j")).to_i - (Date.parse(post.created_at.to_s)).strftime("%j").to_i %> days remaining)</small></span></strong></td>
            </tr>

        <% end %>
      <% end %>
    <% end %>
  <% end %>
    </table>
    <!-- border-left&#58;1px solid lightgray; margin-left&#58;16px; &#35; -->
    <br />
    <b>Click below to visit the google group for <%= @user.name %></b>
    <br />
    <div style="padding-top:12px">
      <% if @user.group_url!=nil %>
        
          <div style="padding-top:0px">
            <a href="<%= @user.group_url %>" target= "_blank" class="cnt" style="text-decoration:none"> Discussion Forum</a>
          </div>

        
      <% else %>
        <div style="text-align:center;border: 2px lightgray;border-radius:2px;background-color: white;color:red;height: 45px; width: 200px" onmouseover="this.style.background='#e7e7e7';" onmouseout="this.style.background='white';">
        This class does not has a google group yet.
        </div>
      <% end %>
    </div>
    <div style="padding-left:0px">
          <hr style="border-bottom: 1px solid lightgray; width: 220px"/>
    </div>

    <table style="border-collapse:collapse; width:227px; ">
            <thead>
                <tr>
                   <th style="color:gray;padding-left:0px;text-align:center">Files uploaded</th>
               </tr>
               <tr style="border-bottom:0px solid black;">
                   <th style="padding:5px; text-align:left"><em>Attatched files</em></th>
                   <th style="padding:0px 0px 0px 10px"><em>By User</em></th>
               </tr>
            </thead>
            <tbody>
              <% @f = 0 %>
              <% @arr.each do|m| %>
                  <%  for post in Micropost.all %>
                    <% if post.id==m %>
                          <% if post.attach.exists? %>

                                <% @f+=1 %>
                                   <tr>
                                     <td style="padding:5px;text-align:left"><a href="<%= post.attach.url %>">

                                       <%= post.attach_file_name %></a></td>

                                     <td style="padding:5px"><%= post.user.name %></td>    
                                  </tr>
                          <% end %>
                    <% end %>
                  <% end %>
              <% end %>
              <% if @f==0%>
                              <tr>
                              <td style="padding:5px;text-align:left"> No files have been uploaded</td>
              <% end %>
            </tbody>
    </table>
  </div>
    <% end %>
  


</div>
</div>
</div>
</body>
<script>
$(document).ready(function(){
  $('body').css('background-color', '#e7e5e5');
});
</script>

app/views/users/edit.html.erb
<div class="container">
<% provide(:title, "Edit user") %> 
<h1>Update your profile</h1>

<div class="row">
  <div class="span6 offset3">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>
      <%= f.label :img %>
      <%= f.text_field :img %>
      
      <%= f.label :name %>
      <%= f.text_field :name %>

      <%= f.label :email %>
      <%= f.text_field :email %>

      <% if (current_user.designation=="class") %>

      <%= f.label :group_url %>
      <%= f.text_field :group_url %>

      <% end %>

      <%= f.label :password %>
      <%= f.password_field :password %>

      <%= f.label :password_confirmation, "Confirm Password" %>
      <%= f.password_field :password_confirmation %>

      <%= f.submit "Save changes", class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>
</div>