config/routes.rb
SimpleApp::Application.routes.draw do
  
  resources :profiles
  
  

   resources :users do
    member do
      get :following, :followers
    end
  end
  resources :sessions, only: [:new, :create, :destroy]
  resources :microposts, only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]

  root to: 'static_pages#home'
  match '/signup',  to: 'users#new'
  match '/help',    to: 'static_pages#help'
  match '/search',   to: 'static_pages#search'
  match '/about',   to: 'static_pages#about'
  match '/contact', to: 'static_pages#contact'
  match '/signin',  to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete
  match '/department', to: 'static_pages#department'
  match '/research', to: 'static_pages#research'

end

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-error">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li>* <%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_feed.html.erb
<% if @feed_items.any? %>
  <ol class="microposts">
    <%= render partial: 'shared/feed_item', collection: @feed_items %>
  </ol>
  <%= will_paginate @feed_items %>
<% end %>

app/views/shared/_feed_item.html.erb
<li id="<%= feed_item.id %>">
  <% if feed_item.attach.exists? %>
  <a href="<%= feed_item.attach.url %>">
    <b>Attachment</b></a>
    <br />
  <% end %>
  <span class="user">
    <%= link_to feed_item.user.name, feed_item.user %>
  </span>
  <span class="content"><%= feed_item.content %></span>
  <span class="timestamp">
    Posted <%= time_ago_in_words(feed_item.created_at) %> ago.
  </span>
    <% if current_user?(feed_item.user) %>
    <%= link_to "delete", feed_item, method: :delete,
                                     data: { confirm: "You sure?" },
                                     title: feed_item.content %>
  <% end %>
</li>

app/views/shared/_micropost_form.html.erb
<%= form_for(@micropost, html: { multipart: true }) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <div class="field">
    <%= f.text_area :content, placeholder: "Compose new micropost..." %>
  </div>
  <p><b>Attachment</b><br />
  	<%= f.file_field :attach %>
  </p>
  <%= f.submit "Post", class: "btn btn-large btn-primary" %>
<% end %>

app/views/shared/_micropost_form1.html.erb
<script type="text/javascript" src="http://js.nicedit.com/nicEdit-latest.js"></script>
<script src="http://code.jquery.com/ui/1.10.3/jquery-ui.js"></script>
<link rel="stylesheet" href="http://code.jquery.com/ui/1.10.3/themes/smoothness/jquery-ui.css" />
 <script type="text/javascript">
        bkLib.onDomLoaded(function() { nicEditors.allTextAreas() });
  </script>
 
  <script>
  
  $(document).ready(function(){
    $("#datepicker").datepicker();
    $("#dead").css("display","none");
    $(".field").css("display","none");
    $("#classes").css("display","none");
    $("#attach").css("display","none");
    $("#gen").change(function(){
      $(".field").slideDown("slow");
      $("#attach").slideDown("slow");
      $("#classes").slideDown("slow");
      $("#dead").slideUp("slow");
    });
    $("#asn").change(function(){
      $(".field").slideDown("slow");
      $("#attach").slideDown("slow");
      $("#dead").slideDown("slow");
      $("#classes").slideDown("slow");
      $( "#datepicker" ).datepicker( "option", "dateFormat", "yy-mm-dd" );
    });
    $("#pol").change(function(){
      $(".field").slideUp("slow");
      $("#dead").slideUp("slow");
      $("#attach").slideUp("slow");
    });
  }); 
  </script>
<%= form_for(current_user.microposts.new, html: { multipart: true }) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <div style="background-color: #f3f3f3">
  <span style="font-size: 27px; font-family: Verdana; color: #2466A8; padding: 7px">Kindly choose the kind of post... </span>
  <br />
  <div style="padding-left: 7px">
  <%= f.radio_button :tyype, "Assignment", :id => 'asn' %> Assignment
  &nbsp;&nbsp;<%= f.radio_button :tyype, "General", :id => 'gen' %> General
  &nbsp;&nbsp;<%= f.radio_button :tyype, "Poll", :id => 'pol' %> Poll
  </div>
  <div class="field" style="padding-top: 7px;">
    <%= f.text_area :content, class: "textarea1" %>
  </div>
  <div id="attach">
  <p>Attachment<br />
    <%= f.file_field :attach %>
  </p>
</div>
  <div id="dead" style="padding: 7px">
    <h3>Choose a deadline</h3>
  <%= f.text_field :deadline, :id => 'datepicker', class: "input-medium" %>
</div>
  <div id="classes" style="padding: 7px">
  <% if current_user.followed_users.count!=0 %>
  <hr />
  <h3>Choose a class to post</h3>
  
    <% for usr in current_user.followed_users %>
  <%= f.radio_button :group_id, usr.id %><%= usr.name %>&nbsp;&nbsp;&nbsp;
  <% end %>
  <% end %>

  <br />
  <div style="padding-top:20px; padding-left: 80px">
  <%= f.submit "Post", class: "btn btn-large btn-primary" %>
</div>
</div>
<% end %>

app/views/shared/_stats.html.erb
<% @user ||= current_user %>
<div class="stats">
  
  <a href="<%= following_user_path(@user) %>">
    <strong id="following" class="stat">
    	<% if @user.designation=="teacher" %>
     &nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Teaching &nbsp;<%= @user.followed_users.count %> &nbsp;Classes
      <% else %>
      Attending &nbsp;<%= @user.followed_users.count %> &nbsp;Classes
      <% end %>
    </strong>
  </a>
</div>

app/views/shared/_user_info.html.erb
<a href="<%= user_path(current_user) %>">
	<%=current_user.name %>
	

   


<span>
  <%= pluralize(current_user.microposts.count, "micropost") %>
</span>