config/routes.rb
SimpleApp::Application.routes.draw do
  
  resources :profiles
  
  

   resources :users do
    member do
      get :following, :followers
    end
  end
  resources :sessions, only: [:new, :create, :destroy]
  resources :microposts, only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]

  root to: 'static_pages#home'
  match '/signup',  to: 'users#new'
  match '/help',    to: 'static_pages#help'
  match '/search',   to: 'static_pages#search'
  match '/about',   to: 'static_pages#about'
  match '/contact', to: 'static_pages#contact'
  match '/signin',  to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete
  match '/department', to: 'static_pages#department'
  match '/research', to: 'static_pages#research'

end

app/views/layouts/_footer.html.erb
<div class="container">
<footer class="footer">
  <small>
    Created by Rishu Raj
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
      
    </ul>
  </nav>
</footer>
</div>

app/views/layouts/_header.html.erb
<% if signed_in? %>
<% nam=current_user.name %>
<% else %>
<% nam="Home" %>
<% end %>
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="navbar-inner">
  
      <%= link_to "ITSpace", department_path, id: "logo", :style => "padding-left: 200px" %>
      <nav>
        <ul class="nav pull-right">
          <% if signed_in? && current_user.designation!="class" %>
          <li><%= link_to nam, root_path %></li>
          <% end %>
          
          <li><%= link_to "Search", search_path %></li>

          <% if signed_in? %>
            <% if current_user.admin? %>
            <li><%= link_to "All Users", users_path %></li>
            <% end %>
            <li><%= link_to "Research Portal", research_path %></li>
            <li id="fat-menu" class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                Classes <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <% for user in User.all.each do %>
                <% if user.designation=="class" %>
                <li><%= link_to user.name, user %></li>
                <% end %>
                <% end %>
                <% if current_user.admin? %>
                <li class="divider"></li>
                <li><%= link_to "New Class", new_user_path %></li>
                <% end %>
              </ul>
            <li id="fat-menu" class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                Account <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to "Profile", current_user %></li>
                <li><%= link_to "Settings", edit_user_path(current_user) %></li>
                <li class="divider"></li>
                <li>
                  <%= link_to "Sign out", signout_path, method: "delete" %>
                </li>
              </ul>
            </li>
          <% else %>
            <li><%= link_to "Sign in", signin_path %></li>
          <% end %>
        </ul>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag    "application", media: "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>    
  </head>
  <body>
    <%= render 'layouts/header' %>
  
      <div class="container">
      <% flash.each do |key, value| %>
        <div class="alert alert-<%= key %>"><%= value %></div>
      <% end %>
      </div>
      <%= yield %>

      <%= render 'layouts/footer' %>
    
  </body>
</html>